# Generated by Django 3.0.5 on 2020-04-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_id',
            new_name='channel_uid',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_id',
            new_name='video_uid',
        ),
    ]
